import React from 'react';
import { useRouter } from '../../lib/router';
import { ArrowLeft, Image as ImageIcon, Search } from 'lucide-react';
import { motion } from 'motion/react';

export function LessonPhotos() {
  const { navigate } = useRouter();

  return (
    <motion.div initial={{ opacity: 0, x: 50 }} animate={{ opacity: 1, x: 0 }} className="space-y-6 max-w-3xl mx-auto">
      <div className="flex items-center space-x-4">
        <button onClick={() => navigate('dashboard')} className="p-2 bg-slate-100 hover:bg-slate-200 rounded-full transition-colors">
          <ArrowLeft className="w-5 h-5 text-slate-700" />
        </button>
        <span className="text-sm font-semibold text-blue-600 uppercase tracking-wider">Lesson Player</span>
      </div>

      <h1 className="text-3xl font-bold text-slate-900">Impossible Photos</h1>
      
      <div className="bg-white rounded-2xl overflow-hidden shadow-sm border border-slate-200">
        <div className="aspect-video bg-slate-200 relative flex items-center justify-center">
          <ImageIcon className="w-16 h-16 text-slate-400" />
          <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent flex items-end p-6">
            <p className="text-white font-medium text-lg">Spotting AI-Generated and Manipulated Images</p>
          </div>
        </div>
        
        <div className="p-6 md:p-8 space-y-6">
          <p className="text-lg text-slate-700 leading-relaxed">
            With modern technology, seeing is no longer believing. Images can be easily manipulated or completely generated by AI. Here are key things to look out for:
          </p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-100">
              <h4 className="font-bold text-slate-900 flex items-center mb-2">
                <Search className="w-4 h-4 mr-2 text-blue-600" /> Check the hands & text
              </h4>
              <p className="text-sm text-slate-600">AI often struggles with generating realistic hands, fingers, and background text (which often looks like gibberish).</p>
            </div>
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-100">
              <h4 className="font-bold text-slate-900 flex items-center mb-2">
                <Search className="w-4 h-4 mr-2 text-blue-600" /> Lighting & shadows
              </h4>
              <p className="text-sm text-slate-600">Look for shadows that go in different directions or lighting that doesn't match the environment.</p>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
