import { useState } from "react";
import { User, Heart, Repeat, Share2, Hand, Image as ImageIcon, HelpCircle, CheckCircle, Lightbulb, CheckSquare, PencilIcon } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { ModuleLayout } from "@/components/layout/ModuleContentLayout";
import "@/pages/courses/firstSteps/styles/module2.css";
import module2Image from "@/assets/courses/firstSteps-l2.jpg";


export function Module2() {
    const [selectedAnswer, setSelectedAnswer] = useState<"correct" | "incorrect" | null>(null);
    const handleAnswer = (answer: "correct" | "incorrect") => {
        setSelectedAnswer(answer);
    };

    const navigate = useNavigate();

    return (
        <ModuleLayout
            eyebrow="Understanding Media"
            title="Module 2: Artificial Intelligence"
            goal="Understand that photographs can now be entirely generated by computers from scratch, and learn to spot visual inconsistencies (artifacts) that reveal them as fake."

            /* =====================================================
               SIMULATION
            ===================================================== */

            simulation={
                <>
                <div className="module-simulation">
                  <div className="module2-social">
                    <div className="module2-social__header">
                      <div className="module2-avatar">
                        <User />
                      </div>
                      <div>
                        <p className="module2-profile-name">
                          NewsFlash
                        </p>
                        <p className="module2-profile-meta">
                          @RealNewsFlash • 2h
                        </p>
                      </div>
                    </div>

                    <div
                      className="module2-image"
                      style={{ backgroundImage: `url(${module2Image})` }}
                    />

                    <div className="module2-social__actions">
                      <button type="button">
                        <Heart />
                        <span>12.4K</span>
                      </button>
                      <button type="button">
                        <Repeat />
                        <span>5.2K</span>
                      </button>
                      <button type="button">
                        <Share2 />
                      </button>
                    </div>
                  </div>

                  <div className="module-tooltip">
                    <p>
                      Notice how this image makes you feel
                      amazed or shocked. AI images are designed
                      to grab your attention instantly so you
                      don't look too closely.
                    </p>
                  </div>
                </div>
                  </>
                }


            /* =====================================================
               EXPLANATION
            ===================================================== */

            explanation={
                <>
                    <div className="module2-explanation">
                        <div className="module2-explanation__title">
                            <HelpCircle color="#e6a33a" />
                            <h2>
                                How to spot an AI image
                            </h2>
                        </div>
                        <p>
                            AI-generated images can look convincing at first
                            glance. Small inconsistencies, called artifacts,
                            can reveal that an image was generated rather than
                            photographed.
                        </p>
                    </div>
                    <div className="module2-clues">
                        <article className="module2-clue">
                        <div className="module2-clue__header">
                            <div className="module2-clue__icon">
                            <Hand />
                            </div>
                            <h3>
                            Clue 1: Hands
                            </h3>
                        </div>
                        <p>
                            Computers are very bad at drawing human
                            hands and feet. Look closely: the computer
                            made a mistake. These physical errors are
                            called "artifacts".
                        </p>
                        </article>
                        <article className="module2-clue">
                        <div className="module2-clue__header">
                            <div className="module2-clue__icon">
                            <ImageIcon />
                            </div>
                            <h3>
                            Clue 2: The Melting World
                            </h3>
                        </div>
                        <p>
                            Now, look at the background behind the
                            person. Do the lines make sense? AI focuses
                            so much on the main subject that it often
                            forgets to make the background obey the
                            laws of physics.
                        </p>
                        </article>
                    </div>
                </>
            }


            /* =====================================================
               ACTIVITY
            ===================================================== */

            activity={
                <div className="module2-activity">
                    <div className="module2-activity__title">
                        <HelpCircle color="#e6a33a" />
                        <h2>
                            Scenario
                        </h2>
                    </div>
                    <p className="module2-activity__question">
                        You see a shocking photo of a politician doing
                        something scandalous. What is the very first thing
                        you should do?
                    </p>


                    <div className="module2-options">
                        <button
                            type="button"
                            className={`module-option ${
                                selectedAnswer === "correct"
                                    ? "module-option--correct"
                                    : ""
                            }`}
                            onClick={() => handleAnswer("correct")}
                        >
                            <span>
                                Zoom in to count their fingers and look
                                for melting backgrounds.
                            </span>

                            {selectedAnswer === "correct" && (
                                <CheckCircle className="module-option__icon" />
                            )}
                        </button>

                        <button
                            type="button"
                            className={`module-option ${
                                selectedAnswer === "incorrect"
                                    ? "module-option--incorrect"
                                    : ""
                            }`}
                            onClick={() => handleAnswer("incorrect")}
                        >
                            Check if a trusted news channel is reporting the same story.

                            {selectedAnswer === "incorrect" && (
                                <span className="module-option__icon">
                                    ✕
                                </span>
                            )}
                        </button>
                    </div>


                    {/* =====================================================
                        INCORRECT FEEDBACK
                    ===================================================== */}

                    {selectedAnswer === "incorrect" && (
                        <div className="module-feedback module-feedback--incorrect">

                            <PencilIcon />

                            <div>
                                <h3>
                                    Not quite.
                                </h3>

                                <p>
                                    The message is designed to make you act quickly
                                    without checking whether it is legitimate.
                                </p>

                                <p>
                                    Don't use the link in the message or enter your
                                    payment details. Instead, open the official delivery
                                    app or website yourself and check the package there.
                                </p>
                            </div>

                        </div>
                    )}

                    {/* =====================================================
                        CORRECT FEEDBACK
                    ===================================================== */}

                    {selectedAnswer === "correct" && (
                        <div className="module-feedback">

                            <CheckSquare />

                            <div>
                                <h3>
                                    Excellent Choice!
                                </h3>

                                <p>
                                    Scammers don't want the 1.99€; they want you to type
                                    your credit card details into their fake website.
                                    Always go directly to the official source.
                                </p>
                            </div>

                        </div>
                    )}

                </div>
            }


            /* =====================================================
               MISSION
            ===================================================== */

            missionTitle="This week's mission: The Detective Game"

            missionDescription={

                <p>
                    Next time you are with your family, open your social
                    media. Try to find one image together and count the
                    fingers of the people in the background. Is it real
                    or AI?
                </p>
            }


            onComplete={() => navigate("/firstSteps/course-info")}

        />

    );
}